//! Runtime configuration (all via env, with sensible local-dev defaults).

use std::path::PathBuf;

use browserid_core::keys::KeyPair;

#[derive(Clone)]
pub struct Config {
    /// Address to bind the HTTP server.
    pub bind: String,
    /// The IdP / app domain (cert issuer, e.g. "mingo.place").
    pub domain: String,
    /// The RP origin that inbound assertions must be audienced to (the SPA origin).
    pub app_origin: String,
    /// The trusted broker domain that may issue certs for external secondary emails.
    pub broker_domain: String,
    /// Path to the persisted Ed25519 keypair (browserid-core StoredKeypair JSON).
    pub key_file: PathBuf,
    /// Path to the SQLite store.
    pub db_path: PathBuf,
    /// Directory holding the IdP's own static assets (provision/auth pages + shims).
    pub static_dir: PathBuf,
    /// Directory holding the mingo-web SPA (served same-origin).
    pub spa_dir: PathBuf,
    /// Optional admin token gating the seed endpoint.
    pub admin_token: Option<String>,
    /// Allow plain-HTTP issuer discovery when verifying inbound assertions (dev only).
    pub allow_http_verify: bool,
}

fn home() -> PathBuf {
    PathBuf::from(std::env::var("HOME").unwrap_or_else(|_| ".".to_string()))
}

fn env_or(key: &str, default: impl Into<String>) -> String {
    std::env::var(key).unwrap_or_else(|_| default.into())
}

impl Config {
    pub fn from_env() -> Self {
        let sbo = home().join(".sbo");
        Self {
            bind: env_or("MINGO_IDP_BIND", "0.0.0.0:7891"),
            domain: env_or("MINGO_IDP_DOMAIN", "mingo.place"),
            app_origin: env_or("MINGO_APP_ORIGIN", "https://mingo.place"),
            broker_domain: env_or("MINGO_BROKER_DOMAIN", "browserid.me"),
            key_file: std::env::var("MINGO_IDP_KEY_FILE")
                .map(PathBuf::from)
                .unwrap_or_else(|_| sbo.join("mingo-idp-key.json")),
            db_path: std::env::var("MINGO_IDP_DB")
                .map(PathBuf::from)
                .unwrap_or_else(|_| sbo.join("mingo-idp.sqlite")),
            static_dir: std::env::var("MINGO_IDP_STATIC")
                .map(PathBuf::from)
                .unwrap_or_else(|_| PathBuf::from("static")),
            spa_dir: std::env::var("MINGO_SPA_DIR")
                .map(PathBuf::from)
                .unwrap_or_else(|_| PathBuf::from("../mingo-web")),
            admin_token: std::env::var("MINGO_ADMIN_TOKEN").ok().filter(|s| !s.is_empty()),
            allow_http_verify: std::env::var("MINGO_ALLOW_HTTP")
                .map(|v| v == "1" || v.eq_ignore_ascii_case("true"))
                .unwrap_or(false),
        }
    }
}

/// Load the IdP keypair, or generate+persist one (browserid-core StoredKeypair format:
/// `{ "secret_key": "<base64url-no-pad 32-byte seed>" }`). Mirrors the broker's
/// `config::load_or_generate_keypair` so a key generated by either tool is interchangeable.
pub fn load_or_generate_keypair(path: &std::path::Path) -> anyhow::Result<KeyPair> {
    use base64::Engine;
    let b64 = base64::engine::general_purpose::URL_SAFE_NO_PAD;

    // Deploy-friendly path: inject the raw base64url seed via env (no shell
    // metacharacters — survives `dokku config:set` cleanly). Highest precedence.
    if let Ok(secret) = std::env::var("MINGO_IDP_SECRET") {
        let seed = b64.decode(secret.trim())?;
        return KeyPair::from_seed(&seed).map_err(|e| anyhow::anyhow!("invalid key seed: {}", e));
    }

    // Or inject the whole StoredKeypair JSON via env (filesystem-free deploy).
    if let Ok(json) = std::env::var("MINGO_IDP_KEY_JSON") {
        let v: serde_json::Value = serde_json::from_str(&json)?;
        let secret = v
            .get("secret_key")
            .and_then(|s| s.as_str())
            .ok_or_else(|| anyhow::anyhow!("MINGO_IDP_KEY_JSON missing secret_key"))?;
        let seed = b64.decode(secret)?;
        return KeyPair::from_seed(&seed).map_err(|e| anyhow::anyhow!("invalid key seed: {}", e));
    }

    if path.exists() {
        let contents = std::fs::read_to_string(path)?;
        let v: serde_json::Value = serde_json::from_str(&contents)?;
        let secret = v
            .get("secret_key")
            .and_then(|s| s.as_str())
            .ok_or_else(|| anyhow::anyhow!("key file missing secret_key"))?;
        let seed = b64.decode(secret)?;
        KeyPair::from_seed(&seed).map_err(|e| anyhow::anyhow!("invalid key seed: {}", e))
    } else {
        let kp = KeyPair::generate();
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).ok();
        }
        let secret = b64.encode(kp.secret_bytes());
        let json = serde_json::to_string_pretty(&serde_json::json!({ "secret_key": secret }))?;
        std::fs::write(path, json)?;
        tracing::info!("generated new mingo-idp key at {}", path.display());
        Ok(kp)
    }
}
